import { Geist, Geist_Mono } from "next/font/google";
import "./../../globals.css";
import Footer from "@/Components/Common/Footer";
import VandorSidebar from "@/Components/Vandor/Common/VandorSidebar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Xplorify | Vandor Dashboard",
    description: "Generated by create next app",
};

export default function Layout({ children }) {
    return (
        <div className="noise-bg relative">
            <VandorSidebar />


            <div className="min-h-screen">
                {children}
            </div>
        </div>
    );
}