import { Geist, Geist_Mono } from "next/font/google";
import "./../../globals.css";
import Footer from "@/Components/Common/Footer";
import VandorSidebar from "@/Components/Vandor/Common/VandorSidebar";
import VandorHeader from "@/Components/Vendor/VandorHeader";
import VandorHeaderMainDash from "@/Components/Vandor/Common/VandorHeader";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Xplorify | Vandor Dashboard",
    description: "Generated by create next app",
};

export default function Layout({ children }) {
    return (
        <div className="noise-bg relative flex min-h-screen" style={{ fontFamily: "var(--font-geist-sans)" }}>
            <VandorSidebar />


            <div className="min-h-screen w-full">
                <VandorHeaderMainDash />
                <div className="md:p-5 p-2">
                    {children}
                </div>
            </div>
        </div>
    );
}