import { Geist, Geist_Mono } from "next/font/google";
import "./../globals.css";
import Footer from "@/Components/Common/Footer";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Xplorify",
    description: "Generated by create next app",
};

export default function Layout({ children }) {
    return (
        <div className="noise-bg relative">
            <div className="container mx-auto border-x border-y-0 border-gray-300 ">
                {children}
            </div>
            <Footer />
        </div>
    );
}